apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nats-iam-broker.fullname" . }}-idp
  labels: {{- include "nats-iam-broker.labels" . | nindent 4 }}
data:
  idp.yaml: |
    {{- with .Values.config.idp }}
    idp:
      {{- toYaml . | nindent 6 }}
    {{- end }}
