{{- if .Values.vault.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nats-iam-broker.fullname" . }}-vault-agent
  labels: {{- include "nats-iam-broker.labels" . | nindent 4 }}
data:
  config-init.hcl: |
    "auto_auth" = {
      "method" = {
        "config" = {
          "role" = "{{ .Values.vault.brokerRole }}"
        }
        "type" = "kubernetes"
        "mount_path" = "{{ .Values.vault.authMount }}"
      }

      "sink" = {
        "config" = {
          "path" = "/vault/secrets/.vault-token"
          "mode" = 0644
        }

        "type" = "file"
      }
    }

    exit_after_auth = true
    pid_file = "/home/vault/.pid"

    {{- with .Values.config.app.natsMicroService }}
    {{- if .encryption.enabled }}
    template = {
      destination = "{{ .encryption.xkeySecret.value }}"
      left_delimiter = "[["
      right_delimiter = "]]"
      contents = <<EOT
      [[- with secret "{{ $.Values.vault.xkeySecret }}" -]]
      [[ .Data.data.privateKey ]]
      [[- end -]]
      EOT
    }
    {{- end }}

    template = {
      destination = "{{ .userCredsFile }}"
      left_delimiter = "[["
      right_delimiter = "]]"
      contents = <<EOT
      [[- with secret "{{ $.Values.vault.mintUserCreds }}" -]]
      [[ .Data.creds ]]
      [[- end -]]
      EOT
    }

    template = {
      destination = "{{ .account.signingNkey.value }}"
      left_delimiter = "[["
      right_delimiter = "]]"
      contents = <<EOT
      [[- with secret "{{ $.Values.vault.mintSigningNKey }}" -]]
      [[ .Data.seed ]]
      [[- end -]]
      EOT
    }
    {{- end }}

    {{- range $.Values.vault.rbacCredentials }}
    template = {
      destination = "/vault/secrets/rbac/{{ .name }}/a-identity.pub"
      left_delimiter = "[["
      right_delimiter = "]]"
      contents = <<EOT
      [[- with secret "{{ .accountPubKey }}" -]]
      [[ .Data.publicKey ]]
      [[- end -]]
      EOT
    }

    template = {
      destination = "/vault/secrets/rbac/{{ .name }}/a-sign.nk"
      left_delimiter = "[["
      right_delimiter = "]]"
      contents = <<EOT
      [[- with secret "{{ .signingNkey }}" -]]
      [[ .Data.seed ]]
      [[- end -]]
      EOT
    }
    {{- end }}

{{- end }}
