apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nats-iam-broker.fullname" . }}-rbac-roles
  labels: {{- include "nats-iam-broker.labels" . | nindent 4 }}
data:
  rbac-roles.yaml: |
    rbac:
      {{- with .Values.config.rbac.roles }}
      roles:
      {{- toYaml . | nindent 6 }}
      {{- end }}
