{{- if .Values.vault.enabled }}
{{ $vaConfig := (index .Values "vault-actions") }}
{{- if $vaConfig.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $vaConfig.secretName }}
  labels: {{- include "nats-iam-broker.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": {{ $vaConfig.hookConfiguration.hook }}
    "helm.sh/hook-weight": {{ (sub $vaConfig.hookConfiguration.hookWeight 1) | quote }}
    "helm.sh/hook-delete-policy": {{ $vaConfig.hookConfiguration.hookDeletePolicy }}
type: Opaque
stringData:
  vault-actions.yaml: |
    vault:
      url: {{ $.Values.vault.url }}
      token: {{ $vaConfig.bootstrapToken }}

    {{- with $vaConfig.config.bootstrap }}
    bootstrap:
      {{- toYaml . | nindent 6 }}
    {{- end }}

    actions:
      - path: sys/policy/{{ $vaConfig.policyName }}
        type: write
        params:
          - k: policy
            v: |
              path "{{ $.Values.vault.mintUserCreds }}" {
                capabilities = ["read"]
              }

              path "{{ $.Values.vault.mintSigningNKey }}" {
                capabilities = ["read"]
              }

              {{- if .Values.config.app.natsMicroService.encryption.enabled }}
              path "{{ $.Values.vault.xkeySecret }}" {
                capabilities = ["read"]
              }
              {{- end }}

              {{- range $.Values.vault.rbacCredentials }}
              path "{{ .accountPubKey }}" {
                capabilities = ["read"]
              }

              path "{{ .signingNkey }}" {
                capabilities = ["read"]
              }
              {{- end }}

      - path: {{ $.Values.vault.authMount }}/role/{{ $.Values.vault.brokerRole }}
        type: write
        params:
          - {
              k: bound_service_account_names,
              v: {{ include "nats-iam-broker.serviceAccountName" . }}
            }
          - { k: bound_service_account_namespaces, v: {{ .Release.Namespace }} }
          - { k: policies, v: {{ $vaConfig.policyName }} }
          - { k: ttl, v: 1h }

    {{- range $vaConfig.config.additionalActions }}
      {{- toYaml . | nindent 6 }}
    {{- end }}

{{- end }}
{{- end }}
