idp:
  client_id: public
  issuer_url:
    - https://oidctest.wsweet.org/

  validation:
    claims:
      - aud
      - iat
      - exp
      - sub
    aud:
      - public
    exp:
      min: 1m0s
      max: 2h
