idp:
  - description: oidctest-private
    client_id: private
    issuer_url: https://oidctest.wsweet.org/

    validation:
      claims:
        - aud
        - iat
        - exp
        - sub
      aud:
        - private
      exp:
        min: 1m0s
        max: 2h

  - description: random-ununused-item
    client_id: random
    issuer_url: https://oidctest.wsweet.org/

    validation:
      claims:
        - aud
        - iat
        - exp
        - sub
      aud:
        - random-aud
      exp:
        min: 1m0s
        max: 2h
